## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
0,0,Barrow,71.2906,-156.7887,-25.58,68,100,10.36,US,overcast clouds
1,1,Nara,34.6851,135.8049,48.96,42,96,10.20,JP,overcast clouds
2,2,Chuy,-33.6971,-53.4616,67.73,87,3,7.90,UY,clear sky
3,3,Vaini,-21.2000,-175.2000,86.16,74,20,9.22,TO,few clouds
4,4,Gondanglegi,-7.7479,112.0132,82.22,77,100,5.48,ID,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min = int(input("Enter minimum temperature criteria "))
max = int(input("Enter maximum temerature criteria "))

Enter minimum temperature criteria 70
Enter maximum temerature criteria 110

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
city_data_df = city_data_df.loc[(city_data_df["Max Temp"]>=min) & (city_data_df["Max Temp"]<=max) ]
city_data_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
3,3,Vaini,-21.2000,-175.2000,86.16,74,20,9.22,TO,few clouds
4,4,Gondanglegi,-7.7479,112.0132,82.22,77,100,5.48,ID,overcast clouds
5,5,Okitipupa,6.5047,4.7839,76.42,94,100,0.74,NG,overcast clouds
8,8,Kapaa,22.0752,-159.3190,75.11,70,28,3.00,US,scattered clouds
10,10,Arraial Do Cabo,-22.9661,-42.0278,72.72,94,100,8.88,BR,moderate rain
...,...,...,...,...,...,...,...,...,...,...
656,656,Poum,-20.2333,164.0167,80.96,77,100,10.18,NC,overcast clouds
661,661,Caravelas,-17.7125,-39.2481,77.54,84,42,7.58,BR,scattered clouds
669,669,Quatre Cocos,-20.2078,57.7625,81.09,90,100,30.60,MU,moderate rain
682,682,Biak,-0.9131,122.8766,79.57,81,100,4.00,ID,light rain
683,683,Bani,18.2833,-70.3333,73.74,76,14,13.02,DO,few clouds

In [5]:
# 4a. Determine if there are any empty rows.
city_data_df.count()

City_ID                245
City                   245
Lat                    245
Lng                    245
Max Temp               245
Humidity               245
Cloudiness             245
Wind Speed             245
Country                244
Current Description    245
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = city_data_df.dropna(how='any')
clean_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
3,3,Vaini,-21.2000,-175.2000,86.16,74,20,9.22,TO,few clouds
4,4,Gondanglegi,-7.7479,112.0132,82.22,77,100,5.48,ID,overcast clouds
5,5,Okitipupa,6.5047,4.7839,76.42,94,100,0.74,NG,overcast clouds
8,8,Kapaa,22.0752,-159.3190,75.11,70,28,3.00,US,scattered clouds
10,10,Arraial Do Cabo,-22.9661,-42.0278,72.72,94,100,8.88,BR,moderate rain
...,...,...,...,...,...,...,...,...,...,...
656,656,Poum,-20.2333,164.0167,80.96,77,100,10.18,NC,overcast clouds
661,661,Caravelas,-17.7125,-39.2481,77.54,84,42,7.58,BR,scattered clouds
669,669,Quatre Cocos,-20.2078,57.7625,81.09,90,100,30.60,MU,moderate rain
682,682,Biak,-0.9131,122.8766,79.57,81,100,4.00,ID,light rain
683,683,Bani,18.2833,-70.3333,73.74,76,14,13.02,DO,few clouds

In [42]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Vaini,TO,86.16,few clouds,-21.2000,-175.2000,
4,Gondanglegi,ID,82.22,overcast clouds,-7.7479,112.0132,
5,Okitipupa,NG,76.42,overcast clouds,6.5047,4.7839,
8,Kapaa,US,75.11,scattered clouds,22.0752,-159.3190,
10,Arraial Do Cabo,BR,72.72,moderate rain,-22.9661,-42.0278,
11,Goundam,ML,73.99,few clouds,16.4145,-3.6708,
12,Saint-Philippe,RE,80.19,heavy intensity rain,-21.3585,55.7679,
14,Port Alfred,ZA,71.04,clear sky,-33.5906,26.8910,
18,Puerto Ayora,EC,77.56,scattered clouds,-0.7393,-90.3518,
19,New Norfolk,AU,72.66,overcast clouds,-42.7826,147.0587,

In [37]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row['Lat']
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [38]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Vaini,TO,86.16,few clouds,-21.2000,-175.2000,Keleti Beach Resort
4,Gondanglegi,ID,82.22,overcast clouds,-7.7479,112.0132,pondok pesantren mamba'ul 'ulum selo rejo
5,Okitipupa,NG,76.42,overcast clouds,6.5047,4.7839,Coastal Hotel & Suites
8,Kapaa,US,75.11,scattered clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
10,Arraial Do Cabo,BR,72.72,moderate rain,-22.9661,-42.0278,Pousada Porto Praia
...,...,...,...,...,...,...,...
656,Poum,NC,80.96,overcast clouds,-20.2333,164.0167,
661,Caravelas,BR,77.54,scattered clouds,-17.7125,-39.2481,Pousada dos Navegantes
669,Quatre Cocos,MU,81.09,moderate rain,-20.2078,57.7625,Sunrise Attitude Hotel
682,Biak,ID,79.57,light rain,-0.9131,122.8766,Penginapan Kim
683,Bani,DO,73.74,few clouds,18.2833,-70.3333,Hospedaje Henriquez

In [39]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [40]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Descriptio</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [41]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))